import Head from "next/head";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";
import Product from "../components/Products";
import { GalleryStyle } from "../styles/GalleryStyle";

// import Link from "next/link";
// import Image from "next/image";

// import bronzeCopper from "../public/assets/images/TexturesCom_BronzeCopper0036_1_M.jpg";

export default function Home() {
  // fetch from strapi
  const [results] = useQuery({ query: PRODUCT_QUERY });
  // data, error, fetching from results
  // console.log(results);
  const { data, error, fetching } = results;

  if (fetching) {
    return <p>Loading...</p>;
  }
  if (error) {
    return <p>Error: {error.message}</p>;
  }
  // console.log(data);
  const products = data.products.data;
  console.log("::: products - index.js ::: ==>", products);

  return (
    <div>
      <Head>
        <title>My Garage Sale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <Image src={bronzeCopper} alt="bronzeCopper" layout="fill" /> */}
        <GalleryStyle>
          <h1>Hello and welcome to My Garage Sale</h1>
          <h3>This is a development test site only, Not in production at this time</h3>
          <br />
          {products.map((product) => (
            <Product key={product.attributes.slug} product={product} />
          ))}
          {/* <Link href={"/about"}>About</Link> */}
        </GalleryStyle>
      </main>

      {/* <footer></footer> */}
    </div>
  );
}
